### ISSUE TITLE
main.py: error during JSON-XML conversion (Windows)

### ISSUE THREAD

**Issue by timmli** [xmg-hhu/xtag2xml#3]
Running `main.py` under Windows stops with an error message during the conversion from JSON to XML: 

> PS C:\Users\Lichte\github\xtag2xml> py .\main.py .\xtag\english\grammar .\output\json .\output\xml true
> Processing XTAG files...
> C:\Users\Lichte\Software\python3\lib\re.py:203: FutureWarning: split() requires a non-empty pattern match.
>   return _compile(pattern, flags).split(string, maxsplit)
> Done!
> Processing JSON files...
> Traceback (most recent call last):
>   File ".\main.py", line 69, in <module>
>     JSONtoXML.getJSONTrees(settings["json_dir"], settings["xml_dir"])
>   File "C:\Users\Lichte\github\xtag2xml\JSONtoXML.py", line 31, in getJSONTrees
>     makeXMLFile(tree, xmlpath+"/"+directory+"/"+jsonfile.split(".", 1)[0]+".xml")
>   File "C:\Users\Lichte\github\xtag2xml\JSONtoXML.py", line 168, in makeXMLFile
>     print(utils.prettifyXMLDocument(output).split(">", 1)[1].strip(), file=xmlfile)
>   File "C:\Users\Lichte\github\xtag2xml\utils.py", line 262, in prettifyXMLDocument
>     reparsed = minidom.parseString(xmlContent)
>   File "C:\Users\Lichte\Software\python3\lib\xml\dom\minidom.py", line 1968, in parseString
>     return expatbuilder.parseString(string)
>   File "C:\Users\Lichte\Software\python3\lib\xml\dom\expatbuilder.py", line 925, in parseString
>     return builder.parseString(string)
>   File "C:\Users\Lichte\Software\python3\lib\xml\dom\expatbuilder.py", line 223, in parseString
>     parser.Parse(string, True)
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 278379

**Comment by timmli** [comment]
Yet with Cygwin and Python 3.4, I don't experience any problems.
